services:
  postgres:
    # Use official multi-arch image (not the public.ecr mirror)
    image: postgres:15
    # On Apple Silicon you can omit platform (native arm64 works), but this is safe cross-host:
    # platform: linux/arm64/v8     # <- uncomment if you’re on Apple Silicon and prefer native
    # platform: linux/amd64        # <- or force amd64 if you want emulation via QEMU
    environment:
      - POSTGRES_DB=clinical_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    restart: unless-stopped

  etl:
    build:
      context: ./etl-service
    environment:
      - DATA_DIR=/data
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=clinical_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/data:ro
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    # platform: linux/arm64/v8  # optional hint if needed

  api:
    build: ./api-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - etl
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:pass@postgres:5432/clinical_data
      - ETL_SERVICE_URL=http://etl:8000
    restart: unless-stopped
    # platform: linux/arm64/v8  # optional hint if needed
