services:
  api:
    build: ./api-service
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - etl
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://user:pass@postgres:5432/clinical_data
      - ETL_SERVICE_URL=http://etl:8000
    restart: unless-stopped

  etl:
    build:
      context: ./etl-service
    environment:
      - DATA_DIR=/data
      - POSTGRES_HOST=postgres
      - POSTGRES_DB=clinical_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
    volumes:
      - ./data:/data:ro
    # Recommended: run uvicorn without --reload inside the container
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    ports:
    - "8000:8000" 

  postgres:
    image: public.ecr.aws/docker/library/postgres:15
    environment:
      - POSTGRES_DB=clinical_data
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"
    volumes:
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    tmpfs:
      - /var/lib/postgresql/data:noexec,nosuid,size=512m
    restart: unless-stopped
